config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :players, only: [:new, :create, :destroy]
  resources :games, only: [:show, :create, :edit, :update, :destroy] do
    resources :questions, only: [:create]
  end
  resources :questions, only: [:show, :destroy] do
    resources :answers, only: [:index, :create]
  end
  resources :answers, only: [:show] do
    resources :votes, only: [:create, :index]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :player
  has_one :game, through: :question
  has_many :votes, dependent: :destroy
  before_destroy { |record| Vote.where(answer: record).delete_all }

  validates_presence_of :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :players, dependent: :destroy
  has_many :answers, through: :questions
  belongs_to :user
  validates :code, uniqueness: true
  before_destroy { |record| Question.where(game: record).delete_all }
  before_destroy { |record| Player.where(game: record).delete_all }

  def host
    user
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_many :answers, dependent: :nullify
  has_many :votes, dependent: :nullify
  before_destroy { |record| Answer.where(player: record).delete_all }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :game
  has_many :answers, dependent: :destroy
  has_many :votes, through: :answers

  validates_presence_of :question

  @@questions = [
    "What is %s's superpower?",
    "What would %s come back as in their second life?",
    "What would %s do if they won the lottery?",
    "Describe %s in three words.",
    "What would %s be arrested for?",
    "If %s could take one thing on a deserted island, what would it be?",
    "What is %s's biggest fear?",
    "What is %s's hidden talent?",
    "If %s were God for a day, what would they do?",
    "What is %s's biggest pet peeve?"
  ]

  def self.questions
    @@questions.sample(10)
  end

  def next
    Question.find_by(game: game, number: number + 1)
  end

  def previous
    Question.find_by(game: game, number: number - 1)
  end
end

app/models/user.rb
class User < ApplicationRecord
  require 'open-uri'

  after_create :set_default_avatar
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_one_attached :avatar
  has_one :player

  def set_default_avatar
    return if avatar.attached?

    LetterAvatar.setup { |config| config.pointsize = 300 }
    avatar.attach(io: URI.open(LetterAvatar.generate(name, 1000)), filename: "#{name}.png", content_type: 'image/png')
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :answer, counter_cache: true
  belongs_to :player
  has_one :question, through: :answer
  validate :not_own

  def not_own
    errors.add(:player, "You can't vote for your own answer") if answer.player == player
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.where(question: params[:question_id])
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.question = Question.find(params[:question_id])
    @answer.player = Player.find_by(user: current_user)
    if @answer.save
      if Answer.where(question: @answer.question).count == @answer.game.players.count
        GameChannel.broadcast_to(
          @answer.game,
          { action: "show answers" }
        )
      end
      redirect_to question_answers_path(@answer.question) # redirect to answers#index
    else
      render :index
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def show
    @players = Player.where(game: @game)
    @player = Player.find_by(user: current_user)
  end

  def create
    code = generate_code
    @game = Game.new(code: code, open: true, user: current_user)

    until @game.save # make sure code unique
      code = generate_code
      @game = Game.new(code: code, open: true)
    end

    @player = Player.create!(user: current_user, game: @game)
    redirect_to game_path(@game) # go to show
  end

  def update
    @game.update(game_params)
    generate_questions
    @game.save
    GameChannel.broadcast_to(
      @game,
      { action: "start", id: @game.questions.first.id }
    )
  end

  def destroy
    @game.destroy
    redirect_to root_path
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:code, :open, :user)
  end

  def generate_code
    letters = ('A'..'Z').to_a
    letters.sample(4).join
  end

  def generate_questions
    players = @game.players.shuffle
    Question.questions.each_with_index do |question, i|
      @game.questions << Question.create!(
        number: i + 1,
        question: format(question, players[i % players.length].user.name),
        game: @game
      )
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home

  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    @player.user = current_user
    @player.game = Game.find_by(code: @player.code.upcase)
    if @player.save
      GameChannel.broadcast_to(
        @player.game,
        { action: "add player", content: render_to_string(partial: "games/player", locals: { player: @player }) }
      )
      redirect_to game_path(@player.game)
    else
      render :new
    end
  end

  def destroy
    if Player.exists?(params[:id])
      @player = Player.find(params[:id])
      if @player.game.players.count == 1
        @player.game.destroy
      elsif @player.game
        Vote.where(answer: Answer.where(player: @player)).delete_all
        Answer.where(player: @player).delete_all
        @player.destroy
      end
    end
    redirect_to root_path
  end

  private

  def player_params
    params.require(:player).permit(:code)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def show
    @answer = Answer.new
  end

  def create
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def index
    answer = Answer.find(params[:answer_id])
    @votes = Vote.where(answer: answer)
    @answers = answer.question.answers.order("votes_count desc")
    @question = Question.find(@votes.first.question.id)
    @game = answer.game
    @player = Player.find_by(user: current_user)
    @players = @game.players.order(points: :desc)
  end

  def create
    @player = Player.find_by(user: current_user)
    @answer = Answer.find(params[:answer_id])
    @answers = @answer.question.answers # used for rerendering answers#index
    @vote = Vote.new(answer: @answer, player: @player)
    if @vote.save
      @answer.player.increment!(:points)
      if @answer.question.votes.count == @answer.game.players.count
        GameChannel.broadcast_to(
          @answer.game,
          { action: "show votes" }
        )
      end
      redirect_to answer_votes_path(@answer)
    else
      render 'answers/index'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<%= link_to answer_votes_path(answer), method: :post, class: "text-white", style: "text-decoration: none;" do %>
  <div class="answer-card">
    <%= answer.answer %>
  </div>
<% end %>

app/views/answers/create.html.erb
<h1>Answers#create</h1>
<p>Find me in app/views/answers/create.html.erb</p>

app/views/answers/index.html.erb
<div class="container">
  <div class="game-container">
    <div id="answers-list" data-game-id="<%= @answers.first.game.id %>">
      <% if Answer.where(question: @answers.first.question).count == @answers.first.game.players.count %>
        <p class="text-center">Pick the best answer</p>
        <% @answers.each do |answer| %>
          <%= render partial: 'answers/answer', locals: {answer: answer} %>
        <% end %>
      <% else %>
        <p>Waiting for answers...</p>
      <% end %>
    </div>
    <% if @vote && @vote.errors.any? %>
      <% @vote.errors.values.each do |error| %>
        <p class="alert alert-danger mt-2"><%= error.first %></p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/answers/new.html.erb
<h1>Answers#new</h1>
<p>Find me in app/views/answers/new.html.erb</p>

app/views/games/_player.html.erb
<li class="my-2">
  <%= cl_image_tag player.user.avatar.key,
      transformation: [{width: 400, height: 400, crop: :fill}, {width: 100, crop: :scale}], class: "avatar" %>
  <%= player.user.name %>
</li>

app/views/games/show.html.erb
<div class="container">
  <div class="game-container">
    <% if current_user == @game.host %>
      <%= link_to game_path(@game), method: :delete, data: {confirm: 'Are you sure you want to cancel this game?'}  do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
    <% else %>
      <%= link_to player_path(@player), method: :delete, data: {confirm: 'Are you sure you want to leave this game?'} do %>
        <i class="fas fa-arrow-left"></i>
      <% end %>
    <% end %>
    <h2 class="text-center">Secret Code: <h1 class="text-center text-primary"><%= @game.code %></h1></h2>

    <div class="dropdown-divider"></div>

    <ul id="players-list" class="align-items-center" data-game-id="<%= @game.id %>" style="list-style-type: none;">
    <% @players.each do |player| %>
      <%= render partial: 'player', locals: {player: player} %>
    <% end %>
    </ul>

    <div class="dropdown-divider mt-0"></div>

    <div class="mt-2">
      <% if current_user == @game.host %>
        <%= simple_form_for @game do |f| %>
          <%= f.hidden_field :open, value: false %>
          <%= f.submit 'Start Game', class: "btn btn-primary w-100" %>
        <% end %>
      <% else %>
        <p>Waiting for host to start the game...</p>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Psych</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <%= favicon_link_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container d-flex justify-content-center" style="height: calc(100vh - 65px)">
  <div class="game-container h-50">
    <div class="d-flex flex-column">
      <%= link_to 'JOIN A GAME', new_player_path, class: "btn btn-outline-primary my-2" %>
      <%= link_to 'START A GAME', games_path, method: :post, class: "btn btn-primary my-2" %>
    </div>
  </div>
</div>

app/views/players/create.html.erb
<h1>Players#create</h1>
<p>Find me in app/views/players/create.html.erb</p>

app/views/players/destroy.html.erb
<h1>Players#destroy</h1>
<p>Find me in app/views/players/destroy.html.erb</p>

app/views/players/new.html.erb
<div class="container">
  <%= simple_form_for @player do |f| %>
    <%= f.input :code %>
    <%= f.submit 'Submit' %>
  <% end %>
</div>

app/views/questions/create.html.erb
<h1>Question#create</h1>
<p>Find me in app/views/question/create.html.erb</p>

app/views/questions/show.html.erb
<div class="container">
  <div class="game-container">
    <h1>Question #<%= @question.number %></h1>
    <p><%= @question.question %></p>

    <%= simple_form_for [@question, @answer] do |f| %>
      <%= f.input :answer, label: false %>
      <%= f.submit 'Submit', class: "btn btn-primary w-100" %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
    <% end %>

  <div class="d-flex">
    <% if user_signed_in? %>
      <% if current_user.player %>
        <% if current_user == current_user.player.game.host %>
          <%= link_to "Leave Game", game_path(current_user.player.game), method: :delete, data: {confirm: 'Are you sure you want to leave this game?'}, class: "btn btn-outline-primary mx-3" %>
        <% else %>
          <%= link_to "Leave Game", player_path(current_user.player), method: :delete, data: {confirm: 'Are you sure you want to leave this game?'}, class: "btn btn-outline-primary mx-3" %>
        <% end %>
      <% end %>
      <div class="dropdown">
        <%= cl_image_tag current_user.avatar.key,
            transformation: [{width: 400, height: 400, crop: :fill}, {width: 100, crop: :scale}],
            class: "avatar dropdown-toggle",
            id: "dropdownMenu",
            data: {toggle: "dropdown"},
            'aria-haspopup': true,
            'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
    <% end %>
  </div>
</div>

app/views/votes/_vote.html.erb
<h1>Hallo</h1>

app/views/votes/index.html.erb
<div class="container">
  <div class="game-container">
    <div id="votes-list" data-game-id="<%= @votes.first.answer.game.id %>">
      <% if @question.votes.count >= @answers.first.game.players.count %>
        <% @answers.each do |answer| %>
          <div class="my-2 d-flex justify-content-between align-items-center" style="list-style-type: none;">
            <%= cl_image_tag answer.player.user.avatar.key, transformation: [{width: 400, height: 400, crop: :fill}, {width: 100, crop: :scale}], class: "avatar" %>
            <div class="vote-card"><%= answer.answer %></div>
            <div class="vote-count"><%= answer.votes.count %></div>
          </div>
        <% end %>
        <div class="dropdown-divider mt-0"></div>
        <% if @answers.first.question.number == @answers.first.game.questions.count %>
          <h1 class="text-center mt-3">Game Summary</h1>
          <div id="summary-list" data-game-id="<%= @game.id %>">
            <% @players.each do |player| %>
              <div class="my-2 d-flex justify-content-between align-items-center" style="list-style-type: none;">
                <%= cl_image_tag player.user.avatar.key, transformation: [{width: 400, height: 400, crop: :fill}, {width: 100, crop: :scale}], class: "avatar" %>
                <div class="vote-card"><%= player.user.name %></div>
                <div class="vote-count"><%= player.points %></div>
              </div>
            <% end %>
          </div>
          <div class="dropdown-divider mt-0"></div>
          <%= link_to "Home", player_path(@player), method: :delete, class: "btn btn-primary w-100" %>
        <% else %>
          <%= link_to "Continue", question_path(@answers.first.question.next), class: "btn btn-primary w-100" %>
        <% end %>
      <% else %>
        <p>Waiting for votes...</p>
      <% end %>
    </div>
  </div>
</div>